preload = /media/beeg/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_DP-1.png
preload = /media/beeg/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_DP-2.png
#preload = /media/Shared/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_HDMI-A-1.png

wallpaper = DP-3, /media/Shared/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_DP-1.png
#wallpaper = DP-2, /media/Shared/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_DP-2.png
#wallpaper = HDMI-A-1, /media/Shared/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_HDMI-A-1.png
wallpaper {
	monitor = DP-1
#	path = /media/Shared/Media/Pics/Wallpapers/split/rwps_97f5fb650b84cae3_DP-1.png
	path = /media/beeg/Media/Pics/Wallpapers/ismoetricplane.png
	fit_mode = center


}
