[opener]
open = [{ run = 'kde-open "$1"', desc = "Open", for = "linux" }]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
extract = [
	{ run = 'ouch d -y %*', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[open]
rules = [
    { mime = "inode/x-empty", use = "edit" },
    { url = "*.conf", use = "edit" },
    { mime = "text/*", use = "edit" },
]

[[plugin.prepend_previewers]]
mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}"
run  = "ouch"

